const RefundPolicy = [
  {
    title: "Client Refund Policy",
    content: [
      "Refunds are only applicable for cancellations made at least 7 days before the service date.",
      "A processing fee of 30% will be deducted from any refund/Advance amount.",
      "No advance amount refunds will be provided for cancellations made within 48 hours of the service date.",
      "Refunds for technical failures in photography or editing will be assessed on a case-by-case basis.",
      "Refund requests must be submitted in writing/Email/through Login with supporting documentation.",
      "Deposits are non-refundable but can be transferred to a future booking.",
      "Refunds for event cancellations due to unforeseen circumstances will be processed within 30 days.",
      "Custom-designed graphics or printed materials are non-refundable after approval.",
      "Makeup and grooming services are non-refundable once the service has started.",
      "If a client is unsatisfied with the service, a resolution process will be followed before a refund is considered.",
      "Refunds will be processed via the same payment method used during booking.",
      "Refunds are not applicable for weather-related cancellations unless stated otherwise in the contract.",
      "Editing or retouching dissatisfaction will not be eligible for a refund once final files are delivered.",
      "Contrashutter reserves the right to issue credits instead of refunds in certain cases.",
      "Any refunds issued will be processed within 10-15 business days.",
      "Services booked under promotional or discounted rates are only 40% refundable of advance amount.",
      "Clients are responsible for ensuring the accuracy of booking details; errors on their part do not qualify for a refund.",
      "Refund policies may be subject to change, and the latest terms will apply at the time of cancellation.",
    ],
  },
  {
    title: "General Conditions for Refunds",
    content: [
      "All refund requests must be submitted via email at Account@contrashutter.com with valid proof.",
      "Refunds are subject to verification and approval by Contrashutter management.",
      "Processing time for refunds is 7-10 business days after approval.",
      "Refunds will only be processed to the original payment method used.",
      "Taxes and service fees (if applicable) are non-refundable.",
      "Any chargeback or fraudulent activity will result in a legal dispute.",
      "Refund policies apply only to direct Contrashutter clients, not third-party service bookings.",
      "If a client provides incorrect details leading to service failure, no refund will be given.",
      "In the case of technical failure from Contrashutter’s side, a full refund will be considered.",
      "Any refund request before 5 days of the service execution date will not be entertained.",
      "Clients must provide supporting documents for cancellation claims (if applicable).",
      "Refund processing charges may be applicable and deducted from the refund amount.",
      "Refunds are not applicable for emergency last-minute execution.",
      "Refunds will not be given for changes in event plans that are not communicated timely.",
      "If the client violates Contrashutter’s policies, no refund will be issued.",
      "Partial refunds will be provided if only a portion of the service is utilized.",
      "Cancellations due to unforeseen situations (e.g., pandemic, natural disasters) will be reviewed case by case.",
      "Refund eligibility is decided by Contrashutter management and will be final.",
      "Refund policy terms are subject to change at any time without prior notice.",
    ],
  },
  {
    title: "Refund Policy for Specific Services",
    content: [
      {
        title: "Photography, Makeup & Decoration Services",
        content: [
          "More than 7 Days Before Event: 70% refund.",
          "Between 3-6 Days Before Event: 50% refund.",
          "Within 48 Hours of the Event: No refund of advance amount.",
          "Incomplete photography shoots due to client delays will not be refunded.",
          "If a client is unhappy with the photos but received what was agreed upon, no refund.",
          "Post-production services (editing, retouching) are non-refundable once work starts.",
          "Sudden changes in event venues without prior notice will not be refunded.",
          "Refunds are not applicable if the client fails to cooperate during the shoot.",
          "If a booked artist is replaced due to emergencies, no refund will be provided.",
          "Cancellation by Contrashutter will result in a full refund.",
          "Clients must request changes within 24 hours of service completion for corrections.",
          "If a client refuses to take final deliverables, no refund will be given.",
          "Non-usage of service after booking is not a valid refund reason.",
          "If images/videos are delivered in promised quality, refunds are not applicable.",
          "Last-minute additional service requests will be charged separately, no refunds if declined.",
          "Refunds for digital photo delivery are not available once files are shared.",
          "Clients cannot demand refunds after accepting and downloading their final images/videos.",
          "Venue lighting conditions are not the responsibility of Contrashutter, and no refund will be given for dissatisfaction due to it.",
          "If Contrashutter needs to reschedule, the client can choose a full refund or a new date.",
          "Deposits for wedding photography are strictly non-refundable after booking confirmation.",
        ],
      },
      {
        title: "Graphic Design & Brand Identity Services",
        content: [
          "If a client cancels before work begins, a 90% refund is applicable.",
          "After initial drafts, only 70% of the payment will be refunded.",
          "If the final design is delivered, no refund will be given.",
          "No refunds will be provided for design dissatisfaction after approval.",
          "Urgent projects with express delivery are non-refundable once started.",
          "If a design brief is unclear and leads to delays, no refund will be given.",
          "Any revisions beyond agreed limits will be chargeable, no refunds for additional work.",
          "If a client refuses to provide necessary content (logos, text), no refund is given.",
          "Changes requested after final submission will require additional payment.",
          "If a client misuses the delivered designs, Contrashutter is not responsible.",
          "Refunds will not be given if a third-party printer incorrectly prints the design.",
          "If a client disputes design ownership after approval, no refund will be processed.",
          "Once editable files are provided, the project is considered complete and non-refundable.",
          "Refunds are not available for marketing consultation fees.",
          "A minimum cancellation fee of 20% applies to all design orders.",
          "If a client fails to provide feedback within 7 days, the project is considered complete.",
          "No refunds for delays caused by client-side decision-making.",
          "A refund request must be made within 48 hours of project cancellation.",
          "Revisions that exceed project scope will be quoted separately, no refund if declined.",
          "Any dispute regarding branding deliverables will be handled through mediation only.",
        ],
      },
    ],
  },
  {
    title: "Service Partner Refund Policy",
    content: [
      "Refunds for services provided by partners are subject to their individual refund policies.",
      "Partners must provide clear refund terms before agreeing to a contract.",
      "Payments made to service partners are non-refundable once the service has started.",
      "If a partner fails to deliver the agreed-upon service, a full refund may be issued to the client.",
      "Service partners must report any cancellations at least 10 days in advance to avoid penalties.",
      "Refunds due to dissatisfaction must be discussed and resolved before processing any repayment.",
      "Contrashutter holds the right to withhold payments in cases of service disputes.",
      "Any breach of contract by a service partner may lead to contract cancellation without refund.",
      "Refunds will not be granted for minor service deviations unless they significantly impact quality.",
      "In cases of force majeure, refunds may be issued at the discretion of Contrashutter.",
      "Payments for completed services are non-refundable, regardless of client satisfaction.",
      "Partners must maintain proof of service delivery to avoid refund claims.",
      "All refund requests must be submitted within 7 days of service completion.",
    ],
  },
  {
    title: "Non-Refundable Cases",
    content: [
      "If the service is partially delivered, no refund will be issued.",
      "No refund will be provided if the client fails to attend the scheduled service without prior notice.",
      "Custom or personalized services are non-refundable.",
      "Digital products are not eligible for refunds once delivered.",
      "Any cancellation due to misconduct or violation of terms will result in no refund.",
    ],
  },
  {
    title: "Force Majeure Policy (Uncontrollable Circumstances)",
    content: [
      "If a service is canceled due to natural disasters, government restrictions, or unforeseen events, clients will be offered a reschedule or a partial refund.",
      "In such cases, a processing fee of 20% will be deducted from the refund amount.",
      "Contrashutter is not liable for cancellations due to factors beyond its control, such as strikes, lockdowns, or weather conditions.",
      "Clients must provide valid proof if they cancel a service due to personal emergencies to qualify for a refund.",
      "The company will handle force majeure cancellations on a case-by-case basis.",
    ],
  },
  {
    title: "Refund Processing & Timeframe",
    content: [
      "Approved refunds will be processed within 10-15 business days.",
      "Refunds will be credited to the original payment method unless otherwise specified.",
      "Transaction fees, gateway charges, or third-party commissions will be deducted from the refund amount.",
      "Clients will receive a refund confirmation email once the transaction is completed.",
      "Any disputes regarding refunds must be raised within 5 days of cancellation for review.",
    ],
  },
];

export default RefundPolicy;
