const ReturnReplacePolicy = [
  {
    title:
      "Return and Replacement Policy for Services (Photography, Makeup, Decoration, and More)",
    content: [
      "Services once availed cannot be returned but exchanged.",
      "If a client is unhappy with service quality, only minor corrections or adjustments will be provided, but a full rework will not be allowed.",
      "Clients must report any service-related issues within 24 hours after completion for eligibility for corrections.",
      "Event-based services (Photography, Makeup, Decoration, Graphics etc.) cannot be redone if missed by the client.",
      "Pre-scheduled services can be modified only if requested at least 7 days in advance.",
      "If a client fails to show up for a scheduled session, the service will be considered completed, and no replacement will be provided.",
      "Minor lighting or editing variations in photography do not qualify for replacements.",
      "If makeup fades due to external factors (weather, sweat, tears, etc.), no replacement or re-service will be provided.",
      "Decoration services will not be replaced or altered once setup is completed at the event venue.",
      "Clients must provide accurate specifications before availing of any service; replacements will not be made due to misunderstandings.",
      "In case of technical issues during photography/videography, only edited photos/videos will be corrected, not the entire shoot.",
      "If makeup products cause an allergic reaction, Contrashutter will not be liable for a replacement.",
      "If a client is dissatisfied due to personal preferences, adjustments will be made within practical limits but without redoing the entire service.",
      "Delays due to client unavailability will not make them eligible for an additional service slot.",
      "In case of force majeure (natural disasters, government restrictions, etc.), Contrashutter will offer a rescheduling option, but no return of service.",
      "If a service was started but could not be completed due to client-side issues, no return or re-service will be provided.",
      "Services cannot be transferred to another client once booked.",
      "If a client chooses the wrong package, it cannot be exchanged after service delivery.",
      "Once a service is booked, switching to a different service is not allowed.",
      "If a client disagrees with Contrashutter’s professional decisions (lighting, angles, makeup shades), no replacement will be offered.",
    ],
  },
  {
    title:
      "Return and Replacement Policy for Digital Products (Edited Photos, Videos, Graphics, etc.)",
    content: [
      "Digital files cannot be returned once delivered.",
      "Only technical errors (missing files, wrong format, or corrupt data) qualify for replacements.",
      "Minor color or lighting differences in edited photos do not qualify for replacements.",
      "A maximum of 2 minor revisions will be allowed per project; additional changes will be chargeable.",
      "If a client downloads and alters the files externally, Contrashutter is not responsible for replacements.",
      "If a file is deleted by the client, Contrashutter is not responsible for restoring it.",
      "Delivered graphic designs cannot be changed or exchanged once approved.",
      "Clients must specify format preferences before delivery; format changes post-delivery will not be accepted.",
      "Watermarked previews will be shared before final delivery; replacements based on dissatisfaction after final delivery will not be considered.",
      "If a file is lost due to client-side technical issues, Contrashutter is not liable for a replacement.",
      "If video footage is too lengthy or too short per the client's perception, it will not be re-edited unless an error was made.",
      "Background music or design choices cannot be changed once finalized.",
      "If a client fails to download digital files within 15 days, Contrashutter is not responsible for re-sending them.",
      "If AI-based editing tools are used for enhancement, client dissatisfaction does not qualify for replacements.",
      "Clients must report digital delivery issues within 48 hours of receiving files.",
      "If a client loses access to the shared link, Contrashutter will only re-share it once.",
      "If the client requests a revision after project closure, a new service charge will apply.",
      "If a third-party service is used (external printers, software compatibility issues, etc.), Contrashutter is not responsible for errors.",
      "If a delivered photo or video has a minor aesthetic issue, it is not eligible for a replacement.",
      "If the client provides incorrect details (event names, date stamps, etc.), replacements will not be provided.",
    ],
  },
  {
    title:
      "Return and Replacement Policy for Physical Products (Albums, Frames, Customized Gifts, etc.)",
    content: [
      "Physical products can be replaced only if damaged upon delivery.",
      "Clients must report any physical damage within 48 hours of receiving the product.",
      "Minor color tone variations in prints do not qualify for replacements.",
      "Customized products (engraved, printed items, etc.) cannot be replaced unless a manufacturing defect is found.",
      "No replacement will be provided if the damage is caused by client mishandling.",
      "Delivery delays caused by couriers do not qualify for replacements.",
      "Once the design is approved for printing, it cannot be changed or replaced.",
      "If a frame or album is broken during shipping, Contrashutter will offer a replacement only if proof is submitted.",
      "If incorrect spelling or information is printed due to client error, replacements will not be made.",
      "Replacement requests after 7 days of delivery will not be accepted.",
    ],
  },
  {
    title: "General Return and Replacement Conditions",
    content: [
      "Clients must inspect items immediately upon delivery and report issues within 48 hours.",
      "If a replacement is issued, the client must return the original product first.",
      "Clients cannot request both a replacement and a refund.",
      "If a replacement is out of stock, an alternative item will be provided.",
      "If an order was custom-made, it cannot be replaced unless defective.",
      "Requests must be made via official email with proper proof.",
      "Clients cannot request partial replacements (e.g., one page of an album).",
      "If an issue is caused by a third-party vendor, Contrashutter is not liable.",
      "If delivery was attempted but the client was unavailable, a replacement is not possible.",
      "Repeated return requests from a single client may be restricted.",
    ],
  },
  {
    title: "Final Terms & Conditions for Return and Replacement",
    content: [
      "Any fraudulent claims for returns/replacements will lead to a permanent ban from future Contrashutter services.",
      "If a client attempts to misuse the return policy (e.g., using a service and then requesting a replacement for unjustified reasons), Contrashutter reserves the right to refuse service.",
      "Clients must clearly specify return reasons—vague complaints will not qualify for replacements.",
      "If a return request is made without sufficient proof (photos, videos, evidence), it will not be processed.",
      "Return and replacement policies are subject to change without prior notice as per Contrashutter’s business needs.",
      "Clients must accept replacement timelines as per Contrashutter’s availability and production schedules.",
      "Legal action may be taken against clients who attempt to defame or falsely accuse Contrashutter to force a return or replacement.",
      "If a product or service has been delivered according to order specifications, replacements will not be allowed.",
      "Any return or replacement disputes will be handled as per Contrashutter’s dispute resolution process.",
      "By availing of Contrashutter’s services/products, the client automatically agrees to these return and replacement policies.",
    ],
  },
];

export default ReturnReplacePolicy;
