const TermsConditions = [
  {
    title: "General Terms & Business Operations",
    content: [
      "Acceptance of Terms – By using Contrashutter’s services, clients and partners agree to all terms & conditions listed here.",
      "Right to Modify – Contrashutter reserves the right to change, update, or modify policies without prior notice.",
      "No Guarantee of Availability – Services are subject to availability and workload, and Contrashutter is not liable for unavailability.",
      "Communication Only Through Official Channels – All bookings, cancellations, and service requests must be made via official email, website, or phone.",
      "Right to Refuse Service – Contrashutter reserves the right to refuse service to any client or partner violating policies or engaging in unethical behavior.",
      "Misuse of Services – Any attempt to misuse Contrashutter’s services for illegal or unethical purposes will lead to immediate termination.",
      "Compliance with Laws – Clients and partners must adhere to all applicable Indian laws and regulations when using Contrashutter’s services.",
      "No Third-Party Liability – Contrashutter is not responsible for failures of third-party vendors, suppliers, or digital platforms.",
      "Independent Contractors – Service partners are independent professionals, and Contrashutter is not responsible for their actions beyond agreed services.",
      "Confidentiality Agreement – All employees, clients, and partners must maintain strict confidentiality regarding company operations and strategies.",
    ],
  },
  {
    title: "Booking & Payment Terms",
    content: [
      "Advance Payment Required – Services are confirmed only after advance payment as per the agreed terms.",
      "Non-Negotiable Fees – All service charges and fees are fixed and non-negotiable, unless otherwise agreed in writing.",
      "Late Payment Penalties – Any delay in payment will result in penalty charges or service suspension.",
      "No Cash Payments – Only official payment modes (bank transfer, UPI, online gateways, cheques) will be accepted.",
      "Instalment Plans – If offered, installment payments must be completed on schedule, or services may be halted.",
      "Taxation Compliance – All payments will be subject to GST and applicable Indian tax laws.",
      "Additional Charges for Custom Requests – Any extra services beyond the booked package will be charged separately.",
      "No Cancellation After Work Begins – Once the service execution starts, cancellation is not allowed, except under special conditions.",
      "Non-Transferable Bookings – Clients cannot transfer their booking to another person or business without prior approval.",
      "Service Modifications – Changes in bookings must be requested at least 7 days in advance and may incur additional charges.",
    ],
  },
  {
    title: "Service Execution & Delivery",
    content: [
      "Work Begins Only After Payment – No work will be initiated until service execution payment is received.",
      "Delivery Timelines Depend on Workload – Deadlines are estimated based on project scope and current workload.",
      "Client’s Responsibility to Provide Inputs – If a client fails to provide necessary materials, Contrashutter is not responsible for delays.",
      "Photography Service Terms – Raw files are not provided, only edited images as per the package.",
      "Design Work Policy – Once a design is finalized, further modifications will be chargeable.",
      "Grooming & Makeup Services – Clients must confirm their preferred look in advance, and no last-minute changes will be entertained.",
      "Brand Identity Services – Business branding and marketing designs require client approval before printing.",
      "Event Photography Delivery – Edited images and videos will be delivered as per agreed timelines, and rush orders will cost extra.",
      "No Responsibility for Venue Restrictions – If a venue restricts photography or decoration, Contrashutter is not liable.",
      "Urgent Delivery Fees Apply – If a client demands an urgent turnaround, extra charges will be applied.",
    ],
  },
  {
    title: "Cancellation, Return & Replacement Policies",
    content: [
      "Cancellation Before Work Starts – If canceled before work begins, only 60% of the payment will be refunded.",
      "No Refunds After 50% Completion – If more than half of the work is done, no refunds will be provided.",
      "Digital Deliverables Are Non-Returnable – Once delivered, digital designs, images, and videos cannot be returned or exchanged.",
      "Physical Deliverables Can Be Replaced If Damaged – If a printed album or physical product is damaged, replacement will be offered only after verification.",
      "Client-Approved Work Cannot Be Changed – If the client approves a design or edit, Contrashutter is not responsible for later dissatisfaction.",
      "Service Partner Failures – If a third-party service provider fails, Contrashutter will not be liable for compensation.",
      "Refund Policy Exceptions – Refunds will only be issued if Contrashutter is unable to deliver the agreed service due to unavoidable reasons.",
      "Replacement Timelines – If a replacement is approved, it will be provided within 10-15 business days.",
      "Damage Claims Require Proof – Clients must submit photo or video proof of any product damage before requesting a replacement.",
      "No Refunds for Preference Changes – If a client dislikes a service after completion, no refund or free replacement will be provided.",
    ],
  },
  {
    title: "Legal & Compliance Policies",
    content: [
      "All Transactions Are Legally Binding – Any agreement made with Contrashutter is enforceable under Indian law.",
      "Intellectual Property Belongs to Contrashutter – Any work created by Contrashutter cannot be reused or sold without permission.",
      "Client Photos May Be Used for Marketing – Unless the client opts out, Contrashutter reserves the right to use photos/videos for promotional purposes.",
      "Unauthorized Use of Branding Is Prohibited – No one is allowed to use Contrashutter’s name, logo, or materials without permission.",
      "Legal Action Against Fraudulent Claims – Any false claim for refunds or disputes will result in legal consequences.",
      "Data Security Compliance – All stored client information is protected under Indian data privacy laws.",
      "Disputes Will Be Resolved Through Arbitration – Before legal action, all disputes must go through arbitration.",
      "Contrashutter Is Not Liable for Natural Disasters – If an event is canceled due to an act of God, Contrashutter is not responsible for refunds.",
      "No Responsibility for Venue Restrictions – If a venue does not allow certain services, Contrashutter will not be held accountable.",
      "Right to Refuse Service in Legal Disputes – If a client is involved in a legal dispute with Contrashutter, future services will be denied.",
    ],
  },
  {
    title: "Service-Specific Terms & Conditions",
    content: [
      "Photography Service Limitations – Only the selected package services will be provided. Extra coverage will be charged separately.",
      "Editing & Retouching Policy – Basic editing is included. Additional retouching requires extra charges.",
      "Makeup & Grooming Finalization – Once makeup and styling are completed, clients cannot demand redoing unless paid for separately.",
      "Decoration Customization – Custom decoration requests must be finalized at least 7 days before the event.",
      "Printing Services Approval Process – Final designs must be approved by clients. Once printed, no reprints will be offered for approval errors.",
      "Graphic Design Work Ownership – Clients receive final files for personal/business use only. Reselling or redistribution is prohibited.",
      "Event Marketing & Branding Materials – Contrashutter reserves the right to use event photos and graphics for promotional purposes unless explicitly restricted by the client.",
      "Social Media Content Services – Any social media marketing service includes a fixed number of revisions. Beyond that, extra charges apply.",
      "Raw Footage & Files – Contrashutter does not provide raw footage or raw image files unless agreed upon in advance with an additional charge.",
      "Re-Shoots & Re-Editing – Clients requesting re-shoots must pay additional fees unless an error occurred on Contrashutter’s part.",
    ],
  },
  {
    title: "Product & Deliverables Terms",
    content: [
      "Digital Files Expiry Policy – Edited digital files will be available for 30 days after delivery. Clients must download within this period.",
      "Cloud Storage Access – Clients opting for long-term storage must pay a subscription fee for continued access.",
      "Album & Print Delivery Timelines – Physical album delivery takes 10-20 business days based on workload.",
      "Damage in Transit Policy – If a printed product is damaged during shipping, a replacement will be sent only after verification.",
      "No Responsibility for Third-Party Printing – If a client chooses to print digital designs elsewhere, Contrashutter is not responsible for print quality.",
      "Merchandise & Custom Gifts Policy – Any customized merchandise is non-returnable and non-exchangeable unless defective.",
      "Incorrect Address Issues – If a product is returned due to a wrong address provided by the client, re-delivery will be chargeable.",
      "Defective Product Replacement Window – Any replacement request must be made within 3 days of receiving the product.",
      "Printing Color Variations – Slight color differences between digital previews and printed materials are normal and not a valid reason for replacement.",
      "No Liability for Third-Party Courier Delays – If a courier company causes delays, Contrashutter is not responsible for any inconvenience caused.",
    ],
  },
  {
    title: "Event & Client Responsibilities",
    content: [
      "Client’s Responsibility for Permissions – If an event requires permits for photography or decorations, it’s the client’s duty to obtain them.",
      "Venue Restrictions Are the Client’s Responsibility – If a venue imposes restrictions after booking, Contrashutter will not be liable.",
      "Force Majeure Clause – If an event is canceled due to natural disasters, strikes, or government orders, Contrashutter is not liable for losses.",
      "Food & Accommodation for Long Shoots – If an event is out of town or extends beyond 8 hours, clients must provide food and accommodation for the team.",
      "Outdoor Shoots Are Weather-Dependent – If an outdoor shoot is canceled due to bad weather, clients must reschedule, and additional costs may apply.",
      "Proper Conduct at Events – Clients must ensure their guests and staff treat Contrashutter’s team with respect. Misconduct may result in service withdrawal.",
      "Client’s Responsibility for Backup Plans – If event arrangements fail (e.g., lights, venue access), Contrashutter is not responsible for last-minute adjustments.",
      "No Interference with Shoot – Guests or third-party vendors must not interfere with Contrashutter’s workflow. If disruptions occur, Contrashutter is not liable for missed shots.",
      "Client Must Arrive on Time for Shoots – Any delay caused by the client may lead to additional charges or reduced shoot time.",
      "Unauthorized Photography by Third Parties – If another photographer is hired at the same event without informing Contrashutter, service quality is not guaranteed.",
    ],
  },
  {
    title: "Legal Protection & Compliance",
    content: [
      "No Liability for Client’s Copyright Issues – If a client provides copyrighted music, images, or graphics for their project, Contrashutter is not responsible for legal consequences.",
      "Client Agreement on Model Release – By booking Contrashutter, clients agree that their photos may be used for promotional purposes unless explicitly opted out.",
      "Breach of Contract Consequences – If a client or partner breaches any contract terms, Contrashutter reserves the right to pursue legal action.",
      "Non-Payment Legal Action – If a client fails to pay as agreed, legal action will be taken after repeated reminders.",
      "False Allegations & Defamation Protection – Any attempt to defame Contrashutter with false accusations will result in legal proceedings.",
      "Fraudulent Chargebacks – If a client disputes a legitimate payment without valid reasons, Contrashutter reserves the right to take legal action.",
      "Agreement on Arbitration for Disputes – Any disputes must be resolved through arbitration first, before legal action is considered.",
      "Privacy Policy Adherence – Client and partner data will be protected under India’s Data Protection laws and will not be shared without consent.",
      "No Liability for Government Interventions – If government actions (e.g., new regulations, lockdowns) affect service delivery, Contrashutter will not be held responsible.",
      "Final Decision Rights Rest with Contrashutter – In case of any disputes or policy interpretations, Contrashutter’s management holds the final decision-making authority.",
    ],
  },
  {
    title: "General Terms for Cheque Payments",
    content: [
      "Cheque payments are accepted only from pre-approved clients who have undergone background verification.",
      "All cheques must be 'Account Payee Only' and issued in the name of Contrashutter—third-party or bearer cheques are strictly prohibited.",
      "Cheques must be submitted at least 7 business days before the due date to ensure clearance before service execution.",
      "Services will commence only after cheque clearance—until then, the booking remains in a pending state.",
      "Post-dated cheques (PDC) will not be accepted unless part of a signed contract with clear terms.",
      "Only corporate cheques with company authorization will be considered for high-value transactions.",
      "Clients must submit a declaration form when paying via cheque to confirm their liability in case of non-clearance.",
      "If a cheque exceeds ₹50,000, additional KYC verification will be required before acceptance.",
      "All cheque payments must comply with RBI and Indian banking regulations.",
      "Contrashutter is not responsible for delays in cheque clearance due to banking issues.",
    ],
  },
  {
    title: "Strict Policies for Bounced Cheques & Non-Payment",
    content: [
      "If a cheque bounces, a penalty of ₹1,000 plus bank charges will apply, payable immediately.",
      "For repeated cheque bounces (2 times), future payments from the client will only be accepted via digital methods (UPI, NEFT, IMPS).",
      "Legal action will be taken under Section 138 of the Negotiable Instruments Act for bounced cheques without resolution within 7 days.",
      "Contrashutter will blacklist clients with a history of cheque dishonor and will no longer offer services.",
      "If a cheque is dishonored, the client’s booking will be canceled without refund.",
      "A bounced cheque for an advance payment will lead to immediate cancellation of services with no rescheduling allowed.",
      "If a cheque bounces due to signature mismatch, the client must submit a new cheque within 48 hours.",
      "If a cheque bounces due to 'insufficient funds,' services will be permanently suspended unless full payment is received digitally within 24 hours.",
      "If a client intentionally issues a fraudulent cheque, Contrashutter will take legal action and report the case to financial authorities.",
      "Cheque bounce penalties must be paid before reissuing any new cheque or booking a new service.",
    ],
  },
  {
    title: "No Risk Policies on Cheque-Based Payments",
    content: [
      "Cheque payments are not eligible for cash refunds—all refunds, if applicable, will be issued via digital transfer.",
      "If a cheque-based transaction fails, the client must switch to an alternative payment method within 24 hours to retain their booking.",
      "If a cheque is lost or stolen, Contrashutter is not responsible for any losses or delays.",
      "Clients must provide an alternate payment method in case of cheque rejection due to technical banking errors.",
      "Cheque payments are not allowed for urgent or same-day bookings.",
      "Contrashutter reserves the right to refuse cheque payments for high-risk transactions or new clients.",
      "Cheque payment terms may be changed at any time without prior notice.",
      "If a cheque is found to be tampered with, the case will be immediately escalated for legal proceedings.",
      "No partial payments are accepted via cheque—full payment must be made in one transaction.",
      "All cheque-based transactions must be documented, signed, and acknowledged by both parties.",
    ],
  },
  {
    title: "Security & Fraud Prevention Measures",
    content: [
      "Contrashutter will verify the client’s bank details before accepting a cheque payment.",
      "Any suspicious cheque transactions will be reported to financial authorities immediately.",
      "Clients must sign a declaration that the cheque they provide is valid, funded, and non-fraudulent.",
      "If a cheque is found to be linked to any illegal activity, the service will be terminated immediately.",
      "Contrashutter will not be liable for any cheque-related fraud committed by third parties.",
      "All cheque transactions are subject to strict internal audits for compliance.",
      "A cheque payment confirmation slip will be issued only after successful clearance.",
      "Contrashutter will not accept cheques from individuals with past financial disputes.",
      "If a cheque is deposited wrongly by the client, Contrashutter is not responsible for any loss.",
      "All cheque payment terms are legally binding once the client agrees to use this method.",
    ],
  },
  {
    title: "Special Terms for Refunds & Adjustments",
    content: [
      "Cheque payments are non-refundable once processed.",
      "Any overpaid cheque amount will only be adjusted against future bookings, not refunded in cash.",
      "If a service is canceled, the cheque amount will be adjusted for another service, but no refund will be issued.",
      "If a refund is approved, it will only be processed via bank transfer within 30 working days.",
      "If a client requests a cheque payment stop, Contrashutter will charge a processing fee of ₹500.",
      "Cheque payments are not eligible for emergency refunds.",
      "If a client requests a replacement service instead of a refund, the cheque amount will be adjusted accordingly.",
      "Contrashutter reserves the right to deny refunds on cheque transactions if deemed necessary.",
      "Any refund disputes for cheque payments will be handled through legal arbitration.",
      "Cheque refund requests will not be entertained after 30 days from payment date.",
    ],
  },
  {
    title: "Restrictions & Legal Protections for Contrashutter",
    content: [
      "No credit facilities are offered on cheque payments—full advance payment is mandatory.",
      "Contrashutter is not responsible for any losses due to delayed cheque processing by banks.",
      "All disputes related to cheque payments will be subject to Pune jurisdiction.",
      "Contrashutter has the right to refuse cheque payments from any client without explanation.",
      "If a cheque is mistakenly deposited for the wrong service, no liability falls on Contrashutter.",
      "Clients must provide proper authorization for company-issued cheques.",
      "Cheque payments are not allowed for international clients—only digital transfers are accepted.",
      "Contrashutter will not be liable for bank errors, misplaced cheques, or external fraud.",
      "If a cheque is found invalid after service delivery, the client must pay digitally within 12 hours.",
      "Failure to comply with cheque policies may lead to permanent blacklisting from Contrashutter’s services.",
    ],
  },
];

export default TermsConditions;
