import { z } from "zod"

export const BookingSchema = z.object({
  fullName: z.string().min(2),
  gender: z.enum(["Male", "Female", "Other"]),
  dateOfBirth: z.string(),
  email: z.string().email(),
  phoneNumber: z.string().regex(/^\d{10}$/),
  alternatePhoneNumber: z.string().regex(/^\d{10}$/).optional(),
  addressLine1: z.string().min(1),
  addressLine2: z.string().optional(),
  city: z.string().min(1),
  state: z.string().min(1),
  pincode: z.string().regex(/^\d{6}$/),
  brideFullName: z.string().min(2),
  groomFullName: z.string().min(2),
  relationToBrideOrGroom: z.enum([
    "Bride - Self",
    "Groom - Self",
    "Friend of Bride/Groom",
    "Father of Bride/Groom",
    "Mother of Bride/Groom",
    "Sister of Bride/Groom",
    "Brother of Bride/Groom",
    "Uncle of Bride/Groom",
    "Aunty of Bride/Groom",
    "Relative of Bride/Groom",
    "Event Planner/Coordinator",
  ]),
  marriageCeremonyType: z.enum([
    "Traditional religious Wedding",
    "Court Marriage",
    "Destination Wedding",
    "Theme Wedding",
    "Interfaith Wedding",
    "Other",
  ]),
  otherMarriageCeremonyType: z.string().optional(),
  religiousType: z.enum(["Hinduism", "Muslim", "Christian", "Sikh", "Buddhist", "Jain", "Interfaith", "Other"]),
  otherReligiousType: z.string().optional(),
  stateSpecificWeddingTradition: z.enum([
    "Maharashtra – Maharashtrian Wedding",
    "Gujarat – Gujarati Wedding",
    "Punjab – Punjabi Wedding",
    "Tamil Nadu – Tamilian Wedding",
    "West Bengal – Bengali Wedding",
    "Rajasthan – Rajasthani Wedding",
    "Uttar Pradesh – Awadhi Wedding",
    "Kerala – Malayali Wedding",
    "Karnataka – Kannadiga Wedding",
    "Andhra Pradesh – Telugu Wedding",
    "Other",
  ]),
  otherStateSpecificWeddingTradition: z.string().optional(),
  eventName: z.string().min(2),
  eventDate: z.string(),
  eventStartTime: z.string(),
  eventEndTime: z.string(),
  venueName: z.string().min(2),
  venueAddressLine1: z.string().min(1),
  venueAddressLine2: z.string().optional(),
  venueCity: z.string().min(1),
  venuePincode: z.string().regex(/^\d{6}$/),
  numberOfGuests: z.number().min(1),
  specialRequirements: z.string().optional(),
  sameAsClientAddress: z.boolean(),
  recipientName: z.string().min(2),
  deliveryAddressLine1: z.string().min(1),
  deliveryAddressLine2: z.string().optional(),
  deliveryCity: z.string().min(1),
  deliveryState: z.string().min(1),
  deliveryPincode: z.string().regex(/^\d{6}$/),
  deliveryContactNumber: z.string().regex(/^\d{10}$/),
  additionalDeliveryInstructions: z.string().optional(),
  preferredPhotographyStyle: z.enum(["Candid", "Traditional", "Both"]),
  preferredEditingStyle: z.enum(["Natural", "Glamorous", "Artistic"]),
  referenceFiles: z.array(z.any()).optional(),
  preferredPaymentMethod: z.enum(["UPI", "Credit/Debit Card", "Net Banking", "Cash on Service"]),
  paymentType: z.enum(["Full Payment", "Installments"]),
  agreeToTerms: z.boolean(),
  confirmBookingDetails: z.boolean(),
})

export type Booking = z.infer<typeof BookingSchema>
