import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "@/components/ui/sonner";
import Overlay from "@/components/Overlay";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Contrashutter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} relative antialiased flex flex-col min-h-screen`}
      >
        <Toaster />
        <Navbar />
        <main className="relative flex h-[89.5vh] overflow-hidden">
          <Overlay />
          <Sidebar />
          <section className="overflow-auto w-full">
            <main className="min-h-screen">{children}</main>
          </section>
        </main>
        <Footer />
      </body>
    </html>
  );
}
